name: Compile Pawn

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Pawn Compiler
        run: |
          sudo apt update
          sudo apt install -y unzip wget
          wget https://github.com/compuphase/pawn/releases/download/v3.10.10/pawn-3.10.10-linux.zip
          unzip pawn-3.10.10-linux.zip

      - name: Compile VRP
        run: |
          ./pawncc vrp.pwn

      - name: Upload AMX
        uses: actions/upload-artifact@v3
        with:
          name: compiled-amx
          path: vrp.amx
